import {getRewardSettings,submitNewsLearning,announceReward} from '../../services/learningAddons';
import { DonutCard } from '../../components/VisualAnalytics';
import { newsMonthRange, monthlyNewsActivity, newsErrorMessage } from './newsStats';
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '../../services/supabaseClient';
import { User, Role } from '../../types';
import { FeatureGuide } from '../../components/FeatureGuide';

type Article = { id: string; title: string; content: string | null; url: string | null; is_approved: boolean; created_at: string; keywords: string[] | null; teacher_id?: string };
type Comment = { id: string; userId: string | null; article_id: string; content: string | null; is_passed: boolean; created_at: string };
type Curated = { title: string; content: string; url?: string; keywords?: string[] };
type Notice = { type: 'success' | 'error'; text: string } | null;
type StudentAccount = { accountId: string; balance: number; account_type?: string | null };

const parseData = <T,>(data: unknown): T => typeof data === 'string' ? JSON.parse(data) as T : data as T;
const stripHtml = (value = '') => value.replace(/<[^>]*>/g, '').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ');
const topicEmoji=(keywords:string[]|null)=>keywords?.some(k=>k.includes('물가'))?'🛒':keywords?.some(k=>k.includes('금리'))?'📈':keywords?.some(k=>k.includes('주식'))?'🏢':'💹';
const getFunctionError = async (error: any, fallback: string) => {
  try { const body = await error?.context?.clone?.().json(); const detail=body?.error?.message||body?.error; if(detail) return newsErrorMessage(typeof detail==='string'?detail:JSON.stringify(detail)); } catch { /* not JSON */ }
  return newsErrorMessage(error?.message ? fallback+': '+error.message : fallback);
};
async function invoke<T>(name:string,body:Record<string,unknown>,fallback:string):Promise<T>{const{data,error}=await supabase.functions.invoke(name,{body});if(error)throw new Error(await getFunctionError(error,fallback));const parsed=parseData<any>(data);if(parsed?.error)throw new Error(`${fallback}: ${parsed.error}`);return parsed as T;}
async function invokeAi<T>(action:string,payload:Record<string,unknown>){return invoke<T>('gemini-handler',{action,payload},'AI 서버 요청 실패');}

function Modal({children,onClose,wide=false}:{children:React.ReactNode;onClose:()=>void;wide?:boolean}){return <div className="fixed inset-0 z-[520] flex items-center justify-center bg-slate-950/60 p-4" onClick={onClose}><div className={`max-h-[90vh] w-full overflow-y-auto rounded-[28px] bg-white p-6 shadow-2xl ${wide?'max-w-4xl':'max-w-lg'}`} onClick={e=>e.stopPropagation()}>{children}</div></div>}
function NoticeModal({notice,close}:{notice:Notice;close:()=>void}){if(!notice)return null;return <Modal onClose={close}><div className="text-center"><div className={`mx-auto flex h-14 w-14 items-center justify-center rounded-2xl text-2xl ${notice.type==='success'?'bg-emerald-50 text-emerald-600':'bg-red-50 text-red-600'}`}>{notice.type==='success'?'✓':'!'}</div><p className="mt-4 whitespace-pre-wrap font-bold leading-relaxed text-slate-700">{notice.text}</p><button onClick={close} className="mt-6 w-full rounded-2xl bg-blue-600 py-3 font-black text-white">확인</button></div></Modal>}

function StudentIdentity({user,account}:{user:User;account:StudentAccount|null}){return <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-[24px] border border-blue-100 bg-white px-5 py-4 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-100 text-xl">👤</span><div><p className="text-xs font-bold text-blue-600">뉴스를 학습하는 학생</p><p className="font-black text-slate-900">{user.number?`${user.number}번 `:''}{user.name}</p></div></div><div className="text-right"><p className="text-xs font-bold text-slate-400">개인 계좌 현금</p><p className="text-xl font-black text-blue-700">{account?Number(account.balance||0).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:1}):'확인 중'}{account?user.currencyUnit||'톨':''}</p>{account&&<p className="mt-1 text-[10px] text-slate-400">계좌 {account.accountId.split(' ').pop()}</p>}</div></div>}

function TeacherNews({user}:{user:User}){
  const [articles,setArticles]=useState<Article[]>([]),[comments,setComments]=useState<Comment[]>([]),[students,setStudents]=useState<User[]>([]),[recommended,setRecommended]=useState<Curated[]>([]);
  const [selected,setSelected]=useState<Article|Curated|null>(null),[commentArticle,setCommentArticle]=useState<Article|null>(null),[studentDetail,setStudentDetail]=useState<User|null>(null);
  const [editing,setEditing]=useState<Article|null>(null),[editorOpen,setEditorOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState<Notice>(null);
  const [title,setTitle]=useState(''),[content,setContent]=useState(''),[url,setUrl]=useState(''),[monthOffset,setMonthOffset]=useState(0),[logLimit,setLogLimit]=useState(5);
  const load=useCallback(async()=>{
    const allRows = async (query: () => any) => {
      const rows:any[]=[];
      for(let from=0;;from+=500){const {data,error}=await query().range(from,from+499);if(error)throw error;rows.push(...(data||[]));if(!data||data.length<500)return rows;}
    };
    const [a,u]=await Promise.all([
      allRows(()=>supabase.from('news_articles').select('*').eq('teacher_id',user.userId).order('created_at',{ascending:false}).order('id')),
      allRows(()=>supabase.from('users').select('*').eq('teacher_id',user.userId).eq('role','student').order('number').order('userId'))
    ]);
    const c:Comment[]=[];
    for(let i=0;i<a.length;i+=100)c.push(...await allRows(()=>supabase.from('news_comments').select('*').in('article_id',a.slice(i,i+100).map(x=>x.id)).order('created_at',{ascending:false}).order('id')));
    setArticles(a as Article[]);setComments(c);setStudents(u as User[]);
  },[user.userId]);
  useEffect(()=>{load().catch(e=>setNotice({type:'error',text:e.message||'뉴스 자료를 불러오지 못했습니다.'}));},[load]);
  const search=async()=>{setBusy(true);try{const result=await invoke<{items?:any[]}>('search-news',{keyword:'경제 금융 뉴스'},'네이버 뉴스 검색 실패');const raw=(result.items||[]).map(x=>({title:stripHtml(x.title),description:stripHtml(x.description),originalContent:stripHtml(x.content||''),url:x.originallink||x.link,publishedAt:x.pubDate,source:{name:'네이버 뉴스'}}));if(!raw.length)throw new Error('검색된 뉴스가 없습니다.');const rows=await invokeAi<Curated[]>('recommend_news',{rawNews:raw});setRecommended(rows);setNotice({type:'success',text:`추천 기사 ${rows.length}건을 준비했습니다. 내용을 확인한 뒤 공개하세요.`});}catch(e:any){setNotice({type:'error',text:e.message||'실시간 뉴스를 불러오지 못했습니다.'});}finally{setBusy(false);}};
  const openEditor=(article?:Article)=>{setEditing(article||null);setTitle(article?.title||'');setContent(article?.content||'');setUrl(article?.url||'');setEditorOpen(true);};
  const save=async()=>{if(!title.trim()||!content.trim()){setNotice({type:'error',text:'제목과 내용을 모두 입력해주세요.'});return;}setBusy(true);try{const payload={title:title.trim(),content:content.trim(),url:url.trim(),keywords:editing?.keywords||['경제','학급'],is_approved:true,teacher_id:user.userId};const{error}=editing?await supabase.from('news_articles').update(payload).eq('id',editing.id):await supabase.from('news_articles').insert(payload);if(error)throw error;setEditorOpen(false);await load();setNotice({type:'success',text:editing?'기사를 수정했습니다.':'기사를 학생에게 공개했습니다.'});}catch(e:any){setNotice({type:'error',text:e.message});}finally{setBusy(false);}};
  const approve=async(item:Curated)=>{const{error}=await supabase.from('news_articles').insert({title:item.title,content:item.content,url:item.url||'',keywords:item.keywords||['경제','금융'],is_approved:true,teacher_id:user.userId});if(error){setNotice({type:'error',text:error.message});return;}setRecommended(v=>v.filter(x=>x!==item));setSelected(null);await load();setNotice({type:'success',text:'기사를 학생에게 공개했습니다.'});};
  const remove=async(article:Article)=>{if(!window.confirm(`'${article.title}' 기사를 삭제할까요?`))return;const{error}=await supabase.rpc('delete_article_with_comments',{target_article_id:article.id});if(error)setNotice({type:'error',text:error.message});else{await load();setNotice({type:'success',text:'기사를 삭제했습니다.'});}};
  const range=useMemo(()=>newsMonthRange(monthOffset),[monthOffset]);
  const {monthly,participants,absent}=useMemo(()=>monthlyNewsActivity(comments,students.map(s=>s.userId),range),[comments,students,range]);
  const publishedArticles=articles.filter(a=>a.is_approved);
  useEffect(()=>setLogLimit(5),[monthOffset]);
  const commentsForStudent=(id:string)=>comments.filter(c=>c.userId===id),commentCount=(id:string)=>comments.filter(c=>c.article_id===id).length;
  return <div className="h-full overflow-y-auto bg-slate-50 p-4 md:p-7"><div className="mx-auto max-w-6xl space-y-7">
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-[28px] bg-gradient-to-r from-blue-50 to-white p-5"><div><p className="text-xs font-black tracking-widest text-amber-600">KIDS ECONOMY NEWS</p><div className="mt-1 flex flex-wrap items-center gap-3"><h2 className="text-3xl font-black text-slate-900">경제뉴스 교사페이지</h2><FeatureGuide title="경제뉴스 사용 안내" label="경제뉴스 사용 안내" items={[{title:'뉴스를 준비해요',description:'실시간 추천을 불러오거나 직접 기사를 작성합니다.'},{title:'내용을 검토해요',description:'AI 추천은 교사가 사실과 표현을 확인한 뒤 공개합니다.'},{title:'학습을 확인해요',description:'월간 참여 현황과 학생 의견을 확인합니다.'}]}/></div><p className="mt-1 text-sm text-slate-500">실제 뉴스를 아이들 눈높이로 다듬고 학습 참여를 확인합니다.</p></div><img src="/design/news-ai.png" alt="" className="h-20 w-20 shrink-0 object-contain"/></div>
    <section className="rounded-[28px] border-2 border-amber-200 bg-white p-5 md:p-7 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-black text-amber-700">리얼 뉴스 큐레이션</h3><p className="text-sm text-slate-500">AI 추천 결과를 검토한 뒤 공개하세요.</p></div><div className="flex gap-2"><button onClick={()=>openEditor()} className="rounded-2xl border-2 border-amber-300 bg-white px-4 py-3 text-sm font-black text-amber-700">✍️ 직접 기사</button><button onClick={search} disabled={busy} className="rounded-2xl bg-amber-400 px-5 py-3 text-sm font-black text-amber-950 shadow disabled:opacity-50">{busy?'뉴스 분석 중...':'🔍 실시간 뉴스'}</button></div></div>
      {recommended.length>0&&<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{recommended.map((item,i)=><article key={`${item.title}-${i}`} className="flex flex-col rounded-2xl border border-amber-100 bg-amber-50/40 p-4"><span className="text-3xl">{topicEmoji(item.keywords||[])}</span><h4 className="mt-2 line-clamp-3 font-black text-slate-800">{item.title}</h4><p className="mt-2 line-clamp-3 text-xs leading-relaxed text-slate-500">{item.content}</p><div className="mt-auto flex gap-2 pt-4"><button onClick={()=>setSelected(item)} className="flex-1 rounded-xl bg-white py-2 text-xs font-bold">검토</button><button onClick={()=>approve(item)} className="flex-1 rounded-xl bg-blue-600 py-2 text-xs font-black text-white">승인·공개</button></div></article>)}</div>}
    </section>
    <section><h3 className="mb-3 text-xl font-black text-slate-900">학생에게 공개된 뉴스</h3><div className="grid gap-4 md:grid-cols-2">{publishedArticles.map(a=><article key={a.id} className="overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm"><div className="flex h-28 items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 text-5xl">{topicEmoji(a.keywords)}</div><div className="p-5"><div className="flex flex-wrap gap-1">{(a.keywords||[]).map(k=><span key={k} className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-600">#{k}</span>)}</div><h4 className="mt-2 text-lg font-black text-slate-900">{a.title}</h4><p className="mt-2 line-clamp-2 text-sm leading-relaxed text-slate-500">{a.content}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setSelected(a)} className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold">기사 보기</button><button onClick={()=>setCommentArticle(a)} className="rounded-xl bg-blue-50 px-3 py-2 text-xs font-black text-blue-700">의견 {commentCount(a.id)}개</button><button onClick={()=>openEditor(a)} className="rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700">수정</button><button onClick={()=>remove(a)} className="rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-600">삭제</button></div></div></article>)}{!publishedArticles.length&&<div className="md:col-span-2 rounded-3xl border-2 border-dashed border-slate-200 bg-white p-12 text-center text-slate-400"><img src="/design/empty-news.png" alt="" className="mx-auto h-32 object-contain"/>아직 공개된 기사가 없습니다.</div>}</div></section>
    <section className="space-y-4" aria-label="월간 학습 참여 현황">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-black text-slate-900">월간 학습 참여 현황</h3><p className="text-sm text-slate-500">{range.label} · 한국 시간 기준</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setMonthOffset(v=>v-1)} className="rounded-xl bg-white px-3 py-2 text-sm font-bold shadow-sm">← 이전 달</button><button onClick={()=>setMonthOffset(0)} className="rounded-xl bg-white px-3 py-2 text-sm font-bold shadow-sm">이번 달</button><button onClick={()=>setMonthOffset(v=>Math.min(0,v+1))} disabled={monthOffset===0} className="rounded-xl bg-white px-3 py-2 text-sm font-bold shadow-sm disabled:opacity-40">다음 달 →</button></div></div>
      <div className="grid items-start gap-4 lg:grid-cols-[minmax(0,.9fr)_minmax(0,1fr)_minmax(0,1.2fr)]">
        <div className="grid grid-cols-2 gap-3">{[{label:'현재 공개 기사 수',value:publishedArticles.length,unit:'건',color:'text-slate-800'},{label:monthOffset===0?'이번 달 의견 수':'선택 월 의견 수',value:monthly.length,unit:'건',color:'text-blue-600'},{label:'참여 학생',value:participants.size,unit:'명',color:'text-emerald-600'},{label:'미참여 학생',value:absent.length,unit:'명',color:'text-amber-600'}].map(item=><div key={item.label} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-3"><p className="text-xs font-semibold text-slate-500">{item.label}</p><p className={'mt-2 text-2xl font-black '+item.color}>{item.value}<span className="ml-1 text-xs">{item.unit}</span></p></div>)}</div>
        <div className="min-w-0"><DonutCard title={monthOffset===0?'이번 달 경제 뉴스 참여 현황':range.label+' 참여 현황'} centerLabel="전체 학생" data={[{name:'참여',value:participants.size,details:students.filter(s=>participants.has(s.userId)).map(s=>s.name)},{name:'미참여',value:absent.length,details:students.filter(s=>absent.includes(s.userId)).map(s=>s.name)}]}/></div>
        <section className="min-w-0 rounded-3xl border border-slate-200 bg-white p-4"><h4 className="font-black text-slate-800">최근 학습 참여 로그</h4><p className="mt-1 text-xs text-slate-500">{range.label} · 최신 의견순</p><div className="mt-3 max-h-64 space-y-2 overflow-y-auto pr-1" aria-label="최근 의견 목록">{monthly.slice(0,logLimit).map(c=>{const student=students.find(s=>s.userId===c.userId);return <button key={c.id} onClick={()=>student&&setStudentDetail(student)} className="block w-full rounded-xl bg-slate-50 p-3 text-left hover:bg-blue-50"><span className="text-sm font-bold text-slate-800">{student?.number}번 {student?.name}</span><time className="mt-1 block text-[11px] text-slate-500">{new Date(c.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</time><p className="mt-1 truncate text-xs text-slate-600">{c.content}</p></button>})}{!monthly.length&&<p className="py-8 text-center text-sm text-slate-400">이 달의 참여 기록이 없습니다.</p>}</div>{monthly.length>logLimit&&<button onClick={()=>setLogLimit(n=>n+10)} className="mt-3 w-full rounded-xl border border-blue-100 py-2 text-sm font-bold text-blue-600">더보기 ({monthly.length-logLimit}건 남음)</button>}</section>
      </div>
      <div><h4 className="mb-3 font-black text-slate-800">학생별 학습 기록</h4><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{students.map(s=>{const count=monthly.filter(c=>c.userId===s.userId).length;return <button key={s.userId} onClick={()=>setStudentDetail(s)} className={'min-w-0 rounded-2xl border bg-white p-3 text-left shadow-sm '+(count?'border-emerald-200':'border-slate-200')}><span className="block truncate text-sm font-black text-slate-800">{s.number}번 {s.name}</span><p className="mt-3 text-xs text-slate-500">전체 의견</p><p className="text-xl font-black text-blue-700">{commentsForStudent(s.userId).length}<span className="ml-1 text-xs">개</span></p><p className="mt-2 text-[11px] text-slate-500">선택 월 {count}개 · 기록 보기</p></button>})}</div>{!students.length&&<p className="py-6 text-sm text-slate-500">등록된 학생이 없습니다.</p>}</div>
    </section>

  </div>
  {editorOpen&&<Modal onClose={()=>setEditorOpen(false)}><h3 className="text-2xl font-black">{editing?'기사 수정':'직접 기사 올리기'}</h3><div className="mt-5 space-y-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="기사 제목" className="w-full rounded-2xl border-2 p-3.5"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="초등학생이 이해하기 쉬운 기사 내용" className="min-h-48 w-full rounded-2xl border-2 p-3.5"/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="원문 주소 (선택)" className="w-full rounded-2xl border-2 p-3.5"/></div><button onClick={save} disabled={busy} className="mt-5 w-full rounded-2xl bg-blue-600 py-3 font-black text-white">저장·공개</button></Modal>}
  {selected&&<Modal onClose={()=>setSelected(null)} wide><button onClick={()=>setSelected(null)} className="mb-4 font-bold text-blue-600">← 닫기</button><h3 className="text-2xl font-black">{selected.title}</h3><p className="mt-6 whitespace-pre-line leading-8 text-slate-700">{selected.content}</p>{selected.url&&<a href={selected.url} target="_blank" rel="noreferrer" className="mt-4 inline-block font-bold text-blue-600 underline">원문 확인</a>}{!('id'in selected)&&<button onClick={()=>approve(selected as Curated)} className="mt-6 w-full rounded-2xl bg-blue-600 py-3 font-black text-white">검토 완료 · 학생에게 공개</button>}</Modal>}
  {commentArticle&&<Modal onClose={()=>setCommentArticle(null)}><h3 className="text-xl font-black">{commentArticle.title}</h3><div className="mt-5 space-y-3">{comments.filter(c=>c.article_id===commentArticle.id).map(c=>{const s=students.find(x=>x.userId===c.userId);return <div key={c.id} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black text-blue-600">{s?`${s.number}번 ${s.name}`:'학생'}</p><p className="mt-2 text-sm">{c.content}</p></div>})}</div></Modal>}
  {studentDetail&&<Modal onClose={()=>setStudentDetail(null)}><h3 className="text-xl font-black">{studentDetail.number}번 {studentDetail.name}의 기록</h3><div className="mt-5 space-y-3">{commentsForStudent(studentDetail.userId).map(c=><div key={c.id} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">{articles.find(a=>a.id===c.article_id)?.title||'삭제된 기사'} · {new Date(c.created_at).toLocaleDateString()}</p><p className="mt-2 text-sm">{c.content}</p></div>)}</div></Modal>}
  <NoticeModal notice={notice} close={()=>setNotice(null)}/></div>;
}

function StudentNews({user,onBalanceChanged}:{user:User;onBalanceChanged?:()=>void}){
  const [rewardAmount,setRewardAmount]=useState<number|null>(null);
  useEffect(()=>{let alive=true;if(user.teacher_id)getRewardSettings(user.teacher_id).then(s=>{if(alive)setRewardAmount(s.news);}).catch(()=>{});return()=>{alive=false};},[user.teacher_id]);
  const [articles,setArticles]=useState<Article[]>([]),[selected,setSelected]=useState<Article|null>(null),[comment,setComment]=useState('');
  const [studentAccount,setStudentAccount]=useState<StudentAccount|null>(null),[accountRefresh,setAccountRefresh]=useState(0);
  const [summary,setSummary]=useState<{summary:string;easy_words:{word:string;meaning:string}[]}|null>(null),[notice,setNotice]=useState<Notice>(null),[busy,setBusy]=useState(false);
  useEffect(()=>{supabase.from('news_articles').select('*').eq('teacher_id',user.teacher_id||'').eq('is_approved',true).order('created_at',{ascending:false}).then(({data,error})=>error?setNotice({type:'error',text:'뉴스를 불러오지 못했습니다.'}):setArticles((data||[]) as Article[]));},[user.teacher_id]);
  useEffect(()=>{let active=true;supabase.from('accounts').select('accountId,balance,account_type').eq('userId',user.userId).eq('teacher_id',user.teacher_id||'').then(({data})=>{if(!active)return;const rows=(data||[]) as StudentAccount[];rows.sort((a,b)=>Number(['student','personal'].includes(b.account_type||''))-Number(['student','personal'].includes(a.account_type||'')));setStudentAccount(rows[0]||null)});return()=>{active=false};},[user.userId,user.teacher_id,accountRefresh]);
  const summarize=async()=>{if(!selected)return;setBusy(true);try{setSummary(await invokeAi('summarize',{title:selected.title,content:selected.content||''}));}catch(e:any){setNotice({type:'error',text:e.message});}finally{setBusy(false);}};
  const submit=async()=>{if(!selected||comment.trim().length<20){setNotice({type:'error',text:'기사에 대한 나의 생각을 20자 이상 적어 주세요.'});return;}setBusy(true);try{const check=await invokeAi<{passed:boolean;reason:string}>('verify',{articleContent:selected.content||'',comment:comment.trim(),keywords:selected.keywords||[]});if(!check.passed){setNotice({type:'error',text:check.reason});return;}const result=await submitNewsLearning(user.userId,selected.id,comment.trim());setComment('');announceReward(result.reward,user.currencyUnit||'톨');setNotice({type:'success',text:`${check.reason}\n${result.pending?'의견을 저장했습니다. 국고 잔액이 부족해 보상은 대기 중입니다. 국고 충전 후 다시 제출해 주세요.':result.reward>0?`최초 이수 보상 ${result.reward}${user.currencyUnit||'톨'}을 받았습니다.`:'의견을 저장했습니다. 추가 지급된 보상은 없습니다.'}`});setAccountRefresh(v=>v+1);onBalanceChanged?.();}catch(e:any){setNotice({type:'error',text:e.message||'의견을 저장하지 못했습니다.'});}finally{setBusy(false);}};
  if(selected)return <div className="h-full overflow-y-auto bg-slate-50 p-4 md:p-7"><div className="mx-auto max-w-3xl"><StudentIdentity user={user} account={studentAccount}/><article className="overflow-hidden rounded-[30px] border bg-white"><div className="flex h-48 items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 text-7xl">{topicEmoji(selected.keywords)}</div><div className="p-6 md:p-9"><button onClick={()=>{setSelected(null);setSummary(null);}} className="mb-5 font-bold text-blue-600">← 뉴스 목록</button><h2 className="text-2xl font-black md:text-3xl">{selected.title}</h2><p className="mt-6 whitespace-pre-line text-base leading-8 text-slate-700">{selected.content}</p>{selected.url&&<a href={selected.url} target="_blank" rel="noreferrer" className="mt-5 inline-block font-bold text-blue-600 underline">원문 보기</a>}<div className="mt-7 rounded-3xl bg-blue-50 p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="font-black text-blue-900">AI 쉬운 뉴스 선생님</h3><p className="text-xs text-blue-600">핵심과 어려운 단어를 설명해요.</p></div><button disabled={busy} onClick={summarize} className="rounded-2xl bg-blue-600 px-5 py-3 font-black text-white">쉽게 요약</button></div>{summary&&<div className="mt-4"><p className="whitespace-pre-line font-semibold leading-relaxed">{summary.summary}</p><div className="mt-3 grid gap-2 sm:grid-cols-3">{summary.easy_words.map(w=><div key={w.word} className="rounded-xl bg-white p-3 text-sm"><b className="text-blue-700">{w.word}</b><p className="mt-1 text-xs">{w.meaning}</p></div>)}</div></div>}</div><div className="mt-7 rounded-3xl border-2 border-emerald-100 p-5"><label className="font-black">뉴스를 읽고 든 나의 생각</label><textarea maxLength={5000} value={comment} onChange={e=>setComment(e.target.value)} placeholder="새롭게 알게 된 점이나 생각을 20자 이상 적어 주세요." className="mt-3 min-h-28 w-full rounded-2xl border-2 p-4"/><div className="mt-2 flex justify-between text-xs"><span>{comment.trim().length}자 / 최소 20자</span><span className="font-black text-emerald-600">{rewardAmount===null?'보상 설정 확인 필요':`최초 이수 시 ${rewardAmount}${user.currencyUnit||'톨'} · 기사당 1회`}</span></div><button disabled={busy} onClick={submit} className="mt-3 w-full rounded-2xl bg-emerald-600 py-3.5 font-black text-white">의견 등록하고 보상 받기</button></div></div></article></div><NoticeModal notice={notice} close={()=>setNotice(null)}/></div>;
  return <div className="h-full overflow-y-auto bg-slate-50 p-4 md:p-7"><div className="mx-auto max-w-4xl"><StudentIdentity user={user} account={studentAccount}/><div className="mb-6 flex flex-wrap justify-between gap-3"><div><p className="text-xs font-black tracking-widest text-blue-600">TODAY'S ECONOMY</p><h2 className="mt-1 text-3xl font-black">오늘의 경제뉴스 🗞️</h2><p className="mt-1 text-slate-500">뉴스를 읽고 AI 선생님과 쉽게 배워보세요.</p></div><FeatureGuide title="경제뉴스 학습 안내" items={[{title:'기사를 읽어요',description:'제목을 누르고 내용과 원문을 천천히 읽습니다.'},{title:'AI 요약을 활용해요',description:'쉬운 요약과 단어 설명으로 다시 확인합니다.'},{title:'내 생각을 적어요',description:'복사하지 않고 나의 생각을 20자 이상 적습니다.'}]}/></div><div className="grid gap-5 md:grid-cols-2">{articles.map(a=><button key={a.id} onClick={()=>setSelected(a)} className="group overflow-hidden rounded-[28px] border bg-white text-left shadow-sm transition hover:-translate-y-1 hover:border-blue-300"><div className="flex h-40 items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 text-6xl">{topicEmoji(a.keywords)}</div><div className="p-6"><div className="flex gap-1">{(a.keywords||[]).map(k=><span key={k} className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-600">#{k}</span>)}</div><h3 className="mt-3 text-xl font-black group-hover:text-blue-600">{a.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-relaxed text-slate-600">{a.content}</p><div className="mt-5 flex justify-between border-t pt-4 text-xs"><span className="text-slate-400">{new Date(a.created_at).toLocaleDateString()}</span><span className="font-black text-blue-600">읽어보기 →</span></div></div></button>)}{!articles.length&&<div className="md:col-span-2 rounded-3xl border-2 border-dashed bg-white p-12 text-center text-slate-400"><img src="/design/empty-news.png" alt="" className="mx-auto h-40 object-contain"/>선생님이 뉴스를 준비하고 있습니다.</div>}</div></div><NoticeModal notice={notice} close={()=>setNotice(null)}/></div>;
}
export default function EconomyNewsPanel({user,onBalanceChanged}:{user:User;onBalanceChanged?:()=>void}){return user.role===Role.TEACHER?<TeacherNews user={user}/>:<StudentNews user={user} onBalanceChanged={onBalanceChanged}/>;}
