import {createPortal} from 'react-dom';
import React,{useEffect,useState} from 'react';
import {getRewardSettings,saveRewardSettings,RewardSettings} from '../services/learningAddons';
import {playSound} from '../services/sounds';
export function RewardSettingsButton({teacherId,unit}:{teacherId:string;unit:string}){
 const [open,setOpen]=useState(false),[values,setValues]=useState<RewardSettings>({news:0,reading:0}),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!open)return;let alive=true;setReady(false);setError('');getRewardSettings(teacherId).then(v=>{if(alive){setValues(v);setReady(true);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false};},[open,teacherId]);
 return <><button onClick={e=>{e.stopPropagation();setOpen(true)}} className="ml-auto rounded-xl border border-white/40 bg-white/15 px-3 py-2 text-xs font-bold text-white">경제상식/경제뉴스 보상 설정</button>{open&&createPortal(<div role="dialog" aria-modal="true" aria-label="학습 보상 설정" className="fixed inset-0 z-[550] flex items-center justify-center bg-slate-950/60 p-4 text-left" onClick={e=>e.stopPropagation()}><section className="max-h-[90vh] overflow-y-auto w-full max-w-lg rounded-3xl bg-white p-6 text-slate-800 shadow-xl"><h2 className="text-xl font-black">경제상식/경제뉴스 보상 설정</h2><p className="my-4 text-sm leading-6">경제상식/경제뉴스에서 미션 해결 시 지급할 보상을 결정해 주세요. 보상이 없을 경우는 '0'으로 적어주세요.</p>{(['news','reading'] as const).map(key=><label key={key} className="mb-4 block text-sm font-bold">{key==='news'?'경제뉴스 기사 1개 최초 이수':'경제상식 챕터 1개 최초 이수'} ({unit})<input type="number" min="0" max="1000000" step="1" disabled={!ready||busy} value={Number.isNaN(values[key])?'':values[key]} onChange={e=>setValues({...values,[key]:e.target.value===''?NaN:Number(e.target.value)})} className="mt-2 block w-full rounded-xl border p-3"/></label>)}<p className="text-xs leading-5 text-slate-500">국고에서 지급합니다. 이미 지급한 금액은 바뀌지 않습니다. 경제상식 보상은 퀴즈 기능 도입 후 적용됩니다.</p>{error&&<p role="alert" className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-5 flex gap-3"><button disabled={busy} onClick={()=>setOpen(false)} className="flex-1 rounded-xl bg-slate-100 p-3 font-bold">닫기</button><button disabled={!ready||busy} onClick={async()=>{setBusy(true);setError('');try{await saveRewardSettings(teacherId,values);setOpen(false);}catch(e:any){setError(e.message);}finally{setBusy(false);}}} className="flex-1 rounded-xl bg-blue-600 p-3 font-bold text-white disabled:opacity-40">{busy?'저장 중':'설정 저장'}</button></div></section></div>,document.body)}</>;
}
export function RewardAnimation(){const [reward,setReward]=useState<{amount:number;unit:string}|null>(null);useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const listener=(e:Event)=>{const detail=(e as CustomEvent).detail;if(!(detail?.amount>0))return;setReward(detail);playSound('success-coin');clearTimeout(timer);timer=setTimeout(()=>setReward(null),2800);};window.addEventListener('classbank-reward',listener);return()=>{clearTimeout(timer);window.removeEventListener('classbank-reward',listener);};},[]);return reward?<div role="status" aria-live="polite" className="reward-celebration pointer-events-none fixed inset-x-4 top-16 z-[650] mx-auto w-fit rounded-3xl border border-amber-200 bg-amber-50 px-8 py-5 text-center shadow-xl"><span className="text-3xl">🪙</span><p className="text-xl font-black text-amber-900">+{reward.amount.toLocaleString()}{reward.unit}</p><p className="text-sm text-amber-800">학습 보상이 입금됐어요!</p></div>:null;}
